---
stages:
  - test
  - build

test:
  stage: test
  image:
    name: docker.io/library/golang:1-stretch
  cache: &cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/
  variables: &variables
    GOPATH: "${CI_PROJECT_DIR}/.cache"
  before_script:
    - go mod download
  script:
    - go vet -race ./...
    - go test -race ./...

build:
  stage: build
  image:
    name: docker.io/goreleaser/goreleaser:v0.111.0
    entrypoint: [""]
  dependencies:
    - test
  cache:
    <<: *cache
    policy: pull
  variables: *variables
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    expire_in: 1 week
    paths:
      - dist/*.deb
      - dist/*.rpm
  script:
    - goreleaser release --rm-dist $(test -z "$CI_COMMIT_TAG" && echo --snapshot)

# vim: set sw=2 sts=2 et :
